### ISSUE TITLE
Add card image to tooltip

### ISSUE THREAD

**Issue by Whebon** [Whebon/dale-of-merchants#17]
I'm not sure yet if this is an improvement. The tooltip might get too large.

**Comment by SamiLaakso** [comment]
If the card always pops on top when hovered over, this is not needed, I think.

**Comment by Whebon** [comment]
This is what another bga game (seasons) does:

![image](https://github.com/user-attachments/assets/3cc2d674-5c7c-4b5e-812b-82ab62d928fd)
